name: saga
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^3.3.8
  get: ^4.6.1
  dio: ^4.0.4
  path_provider: ^2.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.2.0
  fluentui_system_icons: ^1.1.161
  extended_image: ^5.1.3
  flutter_launcher_icons: ^0.9.2
  device_info_plus: ^3.2.2
  flutter_spinkit: ^5.1.0
  flutter_swiper: ^1.1.6
  flutter_widget_from_html: ^0.8.3
  extended_text: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: HarmonyOS_Sans
      fonts:
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Black.ttf
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Light.ttf
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf
        - asset: assets/font/HarmonyOS_Sans/HarmonyOS_Sans_Thin.ttf


flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/logo.png"